/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT loopback.cdb */

#define CHIP_5510PG2_2 1

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <log.h>
#include <sts.h>
#include <csl_emif.h>
#include <csl_mcbsp.h>

#ifdef __cplusplus
extern "C" {
#endif

extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern LOG_Obj LOG_system;
extern STS_Obj IDL_busyObj;
extern EMIF_Config emifCfg0;
extern MCBSP_Config mcbspCfg1;
extern MCBSP_Config mcbspCfg2;
extern MCBSP_Handle C55XX_CONTROLHANDLE_hMcbsp;
extern MCBSP_Handle C55XX_DMA_MCBSP_hMcbsp;
extern void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
